---
- name: printing user
  hosts: localhost
  become: true
  vars_files:
    - users.yml
  tasks:
    - name: vars declaring from file
      ansible.builtin.debug:
        msg: "Hi this is {{user}}."
